services:
  postgresDB:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=finanphy
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5436:5432"
volumes:
  postgres: